apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  
spec:
  project: default

  source:
    path: charts/tomcat
    repoURL: https://github.com/nauco/argocd-demo.git
    targetRevision: HEAD

  destination:
    namespace: tomcat
    server: "https://kubernetes.default.svc"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      
